package com.example.hp.heartrytcare.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "BLOOD_PRESSURE_DATA".
 */
public class BloodPressureData {

    private long id;
    /** Not-null value. */
    private String firebase_user_id;
    private int systolic;
    private int diastolic;
    /** Not-null value. */
    private String date;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BloodPressureData() {
    }

    public BloodPressureData(long id) {
        this.id = id;
    }

    public BloodPressureData(long id, String firebase_user_id, int systolic, int diastolic, String date) {
        this.id = id;
        this.firebase_user_id = firebase_user_id;
        this.systolic = systolic;
        this.diastolic = diastolic;
        this.date = date;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFirebase_user_id() {
        return firebase_user_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirebase_user_id(String firebase_user_id) {
        this.firebase_user_id = firebase_user_id;
    }

    public int getSystolic() {
        return systolic;
    }

    public void setSystolic(int systolic) {
        this.systolic = systolic;
    }

    public int getDiastolic() {
        return diastolic;
    }

    public void setDiastolic(int diastolic) {
        this.diastolic = diastolic;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
