package com.example.hp.heartrytcare.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.hp.heartrytcare.db.User;
import com.example.hp.heartrytcare.db.DoctorCode;
import com.example.hp.heartrytcare.db.DoctorPatient;

import com.example.hp.heartrytcare.db.UserDao;
import com.example.hp.heartrytcare.db.DoctorCodeDao;
import com.example.hp.heartrytcare.db.DoctorPatientDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig doctorCodeDaoConfig;
    private final DaoConfig doctorPatientDaoConfig;

    private final UserDao userDao;
    private final DoctorCodeDao doctorCodeDao;
    private final DoctorPatientDao doctorPatientDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        doctorCodeDaoConfig = daoConfigMap.get(DoctorCodeDao.class).clone();
        doctorCodeDaoConfig.initIdentityScope(type);

        doctorPatientDaoConfig = daoConfigMap.get(DoctorPatientDao.class).clone();
        doctorPatientDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        doctorCodeDao = new DoctorCodeDao(doctorCodeDaoConfig, this);
        doctorPatientDao = new DoctorPatientDao(doctorPatientDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(DoctorCode.class, doctorCodeDao);
        registerDao(DoctorPatient.class, doctorPatientDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        doctorCodeDaoConfig.getIdentityScope().clear();
        doctorPatientDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public DoctorCodeDao getDoctorCodeDao() {
        return doctorCodeDao;
    }

    public DoctorPatientDao getDoctorPatientDao() {
        return doctorPatientDao;
    }

}
