package com.example.hp.heartrytcare.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DOCTOR_CODE".
 */
public class DoctorCode {

    private Long id;
    /** Not-null value. */
    private String firebase_user_id;
    private int doctor_code;
    private boolean verified;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DoctorCode() {
    }

    public DoctorCode(Long id) {
        this.id = id;
    }

    public DoctorCode(Long id, String firebase_user_id, int doctor_code, boolean verified) {
        this.id = id;
        this.firebase_user_id = firebase_user_id;
        this.doctor_code = doctor_code;
        this.verified = verified;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFirebase_user_id() {
        return firebase_user_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirebase_user_id(String firebase_user_id) {
        this.firebase_user_id = firebase_user_id;
    }

    public int getDoctor_code() {
        return doctor_code;
    }

    public void setDoctor_code(int doctor_code) {
        this.doctor_code = doctor_code;
    }

    public boolean getVerified() {
        return verified;
    }

    public void setVerified(boolean verified) {
        this.verified = verified;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
