package com.example.hp.heartrytcare.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DOCTOR_PATIENT".
 */
public class DoctorPatient {

    private Long id;
    /** Not-null value. */
    private String doctor_firebase_uid;
    /** Not-null value. */
    private String patient_firebase_uid;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DoctorPatient() {
    }

    public DoctorPatient(Long id) {
        this.id = id;
    }

    public DoctorPatient(Long id, String doctor_firebase_uid, String patient_firebase_uid) {
        this.id = id;
        this.doctor_firebase_uid = doctor_firebase_uid;
        this.patient_firebase_uid = patient_firebase_uid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDoctor_firebase_uid() {
        return doctor_firebase_uid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDoctor_firebase_uid(String doctor_firebase_uid) {
        this.doctor_firebase_uid = doctor_firebase_uid;
    }

    /** Not-null value. */
    public String getPatient_firebase_uid() {
        return patient_firebase_uid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPatient_firebase_uid(String patient_firebase_uid) {
        this.patient_firebase_uid = patient_firebase_uid;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
