package com.example.hp.heartrytcare.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "HEART_RATE_DATA".
 */
public class HeartRateData {

    private Long id;
    /** Not-null value. */
    private String firebase_user_id;
    private int bpm;
    /** Not-null value. */
    private String date;
    private long timestamp;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public HeartRateData() {
    }

    public HeartRateData(Long id) {
        this.id = id;
    }

    public HeartRateData(Long id, String firebase_user_id, int bpm, String date, long timestamp) {
        this.id = id;
        this.firebase_user_id = firebase_user_id;
        this.bpm = bpm;
        this.date = date;
        this.timestamp = timestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFirebase_user_id() {
        return firebase_user_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirebase_user_id(String firebase_user_id) {
        this.firebase_user_id = firebase_user_id;
    }

    public int getBpm() {
        return bpm;
    }

    public void setBpm(int bpm) {
        this.bpm = bpm;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
