package com.example.hp.heartrytcare.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "JOURNAL".
 */
public class Journal {

    private Long id;
    /** Not-null value. */
    private String firebase_user_id;
    private String meals_taken;
    private String heart_rate;
    private String systolic;
    private String diastolic;
    private String temperature;
    private String weight;
    private String medicine_name;
    private String dosage;
    private String pieces;
    private String how_often;
    private String notes;
    /** Not-null value. */
    private String entry_date;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Journal() {
    }

    public Journal(Long id) {
        this.id = id;
    }

    public Journal(Long id, String firebase_user_id, String meals_taken, String heart_rate, String systolic, String diastolic, String temperature, String weight, String medicine_name, String dosage, String pieces, String how_often, String notes, String entry_date) {
        this.id = id;
        this.firebase_user_id = firebase_user_id;
        this.meals_taken = meals_taken;
        this.heart_rate = heart_rate;
        this.systolic = systolic;
        this.diastolic = diastolic;
        this.temperature = temperature;
        this.weight = weight;
        this.medicine_name = medicine_name;
        this.dosage = dosage;
        this.pieces = pieces;
        this.how_often = how_often;
        this.notes = notes;
        this.entry_date = entry_date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFirebase_user_id() {
        return firebase_user_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirebase_user_id(String firebase_user_id) {
        this.firebase_user_id = firebase_user_id;
    }

    public String getMeals_taken() {
        return meals_taken;
    }

    public void setMeals_taken(String meals_taken) {
        this.meals_taken = meals_taken;
    }

    public String getHeart_rate() {
        return heart_rate;
    }

    public void setHeart_rate(String heart_rate) {
        this.heart_rate = heart_rate;
    }

    public String getSystolic() {
        return systolic;
    }

    public void setSystolic(String systolic) {
        this.systolic = systolic;
    }

    public String getDiastolic() {
        return diastolic;
    }

    public void setDiastolic(String diastolic) {
        this.diastolic = diastolic;
    }

    public String getTemperature() {
        return temperature;
    }

    public void setTemperature(String temperature) {
        this.temperature = temperature;
    }

    public String getWeight() {
        return weight;
    }

    public void setWeight(String weight) {
        this.weight = weight;
    }

    public String getMedicine_name() {
        return medicine_name;
    }

    public void setMedicine_name(String medicine_name) {
        this.medicine_name = medicine_name;
    }

    public String getDosage() {
        return dosage;
    }

    public void setDosage(String dosage) {
        this.dosage = dosage;
    }

    public String getPieces() {
        return pieces;
    }

    public void setPieces(String pieces) {
        this.pieces = pieces;
    }

    public String getHow_often() {
        return how_often;
    }

    public void setHow_often(String how_often) {
        this.how_often = how_often;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    /** Not-null value. */
    public String getEntry_date() {
        return entry_date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEntry_date(String entry_date) {
        this.entry_date = entry_date;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
