package com.example.hp.heartrytcare.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LIMIT_VALUES".
 */
public class LimitValues {

    private Long id;
    /** Not-null value. */
    private String firebase_user_id;
    private String bpLimit;
    private String hrLimit;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LimitValues() {
    }

    public LimitValues(Long id) {
        this.id = id;
    }

    public LimitValues(Long id, String firebase_user_id, String bpLimit, String hrLimit) {
        this.id = id;
        this.firebase_user_id = firebase_user_id;
        this.bpLimit = bpLimit;
        this.hrLimit = hrLimit;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFirebase_user_id() {
        return firebase_user_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirebase_user_id(String firebase_user_id) {
        this.firebase_user_id = firebase_user_id;
    }

    public String getBpLimit() {
        return bpLimit;
    }

    public void setBpLimit(String bpLimit) {
        this.bpLimit = bpLimit;
    }

    public String getHrLimit() {
        return hrLimit;
    }

    public void setHrLimit(String hrLimit) {
        this.hrLimit = hrLimit;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
