package com.example.hp.heartrytcare.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "MEDICATION".
 */
public class Medication {

    private Long id;
    /** Not-null value. */
    private String firebase_user_id;
    private String nameOfMed;
    private String dosage;
    private String numberOfMed;
    private String method;
    private String howOften;
    private String time;
    private String startDate;
    private String duration;
    private Boolean alert;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Medication() {
    }

    public Medication(Long id) {
        this.id = id;
    }

    public Medication(Long id, String firebase_user_id, String nameOfMed, String dosage, String numberOfMed, String method, String howOften, String time, String startDate, String duration, Boolean alert) {
        this.id = id;
        this.firebase_user_id = firebase_user_id;
        this.nameOfMed = nameOfMed;
        this.dosage = dosage;
        this.numberOfMed = numberOfMed;
        this.method = method;
        this.howOften = howOften;
        this.time = time;
        this.startDate = startDate;
        this.duration = duration;
        this.alert = alert;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFirebase_user_id() {
        return firebase_user_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirebase_user_id(String firebase_user_id) {
        this.firebase_user_id = firebase_user_id;
    }

    public String getNameOfMed() {
        return nameOfMed;
    }

    public void setNameOfMed(String nameOfMed) {
        this.nameOfMed = nameOfMed;
    }

    public String getDosage() {
        return dosage;
    }

    public void setDosage(String dosage) {
        this.dosage = dosage;
    }

    public String getNumberOfMed() {
        return numberOfMed;
    }

    public void setNumberOfMed(String numberOfMed) {
        this.numberOfMed = numberOfMed;
    }

    public String getMethod() {
        return method;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    public String getHowOften() {
        return howOften;
    }

    public void setHowOften(String howOften) {
        this.howOften = howOften;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getStartDate() {
        return startDate;
    }

    public void setStartDate(String startDate) {
        this.startDate = startDate;
    }

    public String getDuration() {
        return duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    public Boolean getAlert() {
        return alert;
    }

    public void setAlert(Boolean alert) {
        this.alert = alert;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
