package com.example.hp.heartrytcare.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    private int user_id;
    private int user_type;
    /** Not-null value. */
    private String last_name;
    /** Not-null value. */
    private String first_name;
    private String license_number;
    private String email;
    private String contact_number;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, int user_id, int user_type, String last_name, String first_name, String license_number, String email, String contact_number) {
        this.id = id;
        this.user_id = user_id;
        this.user_type = user_type;
        this.last_name = last_name;
        this.first_name = first_name;
        this.license_number = license_number;
        this.email = email;
        this.contact_number = contact_number;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getUser_id() {
        return user_id;
    }

    public void setUser_id(int user_id) {
        this.user_id = user_id;
    }

    public int getUser_type() {
        return user_type;
    }

    public void setUser_type(int user_type) {
        this.user_type = user_type;
    }

    /** Not-null value. */
    public String getLast_name() {
        return last_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLast_name(String last_name) {
        this.last_name = last_name;
    }

    /** Not-null value. */
    public String getFirst_name() {
        return first_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirst_name(String first_name) {
        this.first_name = first_name;
    }

    public String getLicense_number() {
        return license_number;
    }

    public void setLicense_number(String license_number) {
        this.license_number = license_number;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getContact_number() {
        return contact_number;
    }

    public void setContact_number(String contact_number) {
        this.contact_number = contact_number;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
